spring.application.name=projeto-banco-ifsertaope
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

token.personalizado.para.criacao.da.chave.de.autenticacao = gustavo-se-tornando-a-lenda-do-curso
